[versions]
fragment = "1.5.2"
hilt = "2.43.2"
kotlin = "1.7.10"
lifecycle = "2.5.1"
navigation = "2.5.1"
agp = "7.4.0-alpha09"
spotless = "6.10.0"

[libraries]
androidx-activity = "androidx.activity:activity-ktx:1.5.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-legacy = "androidx.legacy:legacy-support-v4:1.0.0"
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-paging-runtime = "androidx.paging:paging-runtime:3.1.1"
androidx-security-crypto = "androidx.security:security-crypto:1.0.0"
androidx-security-identity = "androidx.security:security-identity-credential:1.0.0-alpha03"

build-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

chucker-library = "com.github.chuckerteam.chucker:library:3.5.2"
chucker-no-op = "com.github.chuckerteam.chucker:library-no-op:3.5.2"

google-material = "com.google.android.material:material:1.6.1"
google-dagger = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

square-moshi = "com.squareup.moshi:moshi-kotlin:1.13.0"
square-moshi-converter = "com.squareup.retrofit2:converter-moshi:2.9.0"
square-okhttp-logging = "com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.10"

leakcanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"
lottie = "com.airbnb.android:lottie:5.2.0"
moshi-metadata-reflect = "dev.zacsweers.moshix:moshi-metadata-reflect:0.18.3"
openid-appauth = "net.openid:appauth:0.11.1"
timber = "com.jakewharton.timber:timber:5.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
