[versions]
fragment = "1.4.1"
hilt = "2.42"
kotlin = "1.6.21"
lifecycle = "2.4.1"
navigation = "2.4.2"

[libraries]
androidx-activity = "androidx.activity:activity-ktx:1.4.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-legacy = "androidx.legacy:legacy-support-v4:1.0.0"
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-paging-runtime = "androidx.paging:paging-runtime:3.1.1"
androidx-security-crypto = "androidx.security:security-crypto:1.0.0"
androidx-security-identity = "androidx.security:security-identity-credential:1.0.0-alpha03"

chucker-library = "com.github.chuckerteam.chucker:library:3.5.2"
chucker-no-op = "com.github.chuckerteam.chucker:library-no-op:3.5.2"

google-material = "com.google.android.material:material:1.6.1"
google-dagger = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

square-moshi = "com.squareup.moshi:moshi-kotlin:1.13.0"
square-moshi-converter = "com.squareup.retrofit2:converter-moshi:2.9.0"
square-okhttp-logging = "com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.10"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-ktfmt = "com.facebook:ktfmt:0.37"
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"
lottie = "com.airbnb.android:lottie:5.2.0"
moshi-metadata-reflect = "dev.zacsweers.moshix:moshi-metadata-reflect:0.17.2"
openid-appauth = "net.openid:appauth:0.11.1"
timber = "com.jakewharton.timber:timber:5.0.1"

build-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.7.0"
build-r8 = "com.android.tools:r8:3.3.28"
build-gradle = "com.android.tools.build:gradle:7.2.1"
build-gradle-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21"
build-gradle-dagger = "com.google.dagger:hilt-android-gradle-plugin:2.42"
build-navigation-safeargs = "androidx.navigation:navigation-safe-args-gradle-plugin:2.4.2"

[bundles]
