object Dependencies {
    const val kotlin_version = "1.5.30"
    const val appcompat_version = "1.3.1"
    const val constraint_layout_version = "2.0.4"
    const val core_ktx_version = "1.6.0"
    const val material_version = "1.4.0"
    const val lifecycle_version = "2.3.1"
    const val retrofit_version = "2.9.0"
    const val gradle_version = "7.0.2"
    const val appauth_version = "0.10.0"
    const val crypto_version = "1.0.0"
    const val identity_version = "1.0.0-alpha02"
    const val reflect_version = "0.12.0"
    const val moshi_version = "1.12.0"
    const val hilt_version = "2.38.1"
    const val activity_version = "1.3.1"
    const val nav_version = "2.3.5"
    const val paging_version = "3.0.1"
    const val logging_version = "4.9.1"
    const val leakcanary_version = "2.7"
    const val fragment_version = "1.3.6"
    const val legacy_version = "1.0.0"
    const val chucker_version = "3.5.2"
    const val r8_version = "3.0.65"
    const val lottie_version = "4.1.0"
    const val timber_version = "5.0.1"
}
