name: Android CI

on: push

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: Check codestyle
        uses: gradle/gradle-build-action@v2.2.3
        with:
          arguments: spotlessCheck
